# Set defaults for RedHat
---

- include_vars: "{{ ansible_os_family }}_8.yml"
  when: >
    (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8)
    or
    (ansible_os_family == 'Fedora' and ansible_distribution_major_version|int >= 30)

- include_vars: "{{ ansible_os_family }}.yml"
  when: >
    (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int < 8)
    or
    (ansible_os_family == 'Fedora' and ansible_distribution_major_version|int < 30)
